<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.util.List" %>
<%@ page import="com.example.erp.frontend.promo.PromoCampaignView" %>
<%@ page import="com.example.erp.frontend.promo.PromoOptionsView" %>
<!doctype html>
<html lang="cs"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ERP | Promo kampaně</title><link rel="stylesheet" href="assets/base.css"><link rel="stylesheet" href="assets/promo.css"><link rel="stylesheet" href="assets/promo-form.css"></head>
<body><main class="promo-page"><header class="promo-header"><a href="./" class="back-link">← Aplikace</a><div><span class="eyebrow">PRODEJ / PROMO</span><h1>Promo kampaně</h1><p>Plánujte letákové akce, kontrolujte marži a upravujte jejich průběh.</p></div><button type="button" class="primary" id="add-campaign">+ Nová kampaň</button></header>
<% String error = (String) request.getAttribute("error"); String message = request.getParameter("message"); if (error != null) { %><p class="promo-message error"><%= error %></p><% } if (message != null) { %><p class="promo-message"><%= message %></p><% } %>
<section class="promo-features"><article><b>Plán akce</b><span>Datum, sortiment a cenový rozdíl</span></article><article><b>Alokace prodejen</b><span>Distribuce plánovaného množství</span></article><article><b>Výkon kampaně</b><span>Plán versus skutečný prodej</span></article></section>
<section id="campaigns" class="campaign-section"><div class="section-head"><div><span class="eyebrow">AKTUÁLNÍ KAMPANĚ</span><h2>Řízení průběhu</h2></div><span class="campaign-count"><%= request.getAttribute("campaigns") == null ? 0 : ((List<?>) request.getAttribute("campaigns")).size() %> kampaní</span></div><div class="campaign-list"><% List<PromoCampaignView> campaigns = (List<PromoCampaignView>) request.getAttribute("campaigns"); if (campaigns != null) for (PromoCampaignView campaign : campaigns) { %><article class="campaign-card"><div class="campaign-main"><span class="status-chip status-<%= campaign.status().toLowerCase() %>"><%= campaign.status() %></span><h3><%= campaign.name() %></h3><p><%= campaign.startsOn() %> až <%= campaign.endsOn() %></p></div><dl><div><dt>Běžná cena</dt><dd><%= campaign.regularPrice() %> Kč</dd></div><div><dt>Akční cena</dt><dd><%= campaign.promoPrice() %> Kč</dd></div><div><dt>Plán / skutečnost</dt><dd><%= campaign.plannedQuantity() %> / <%= campaign.actualQuantity() %></dd></div></dl><form method="post" class="campaign-form"><input type="hidden" name="id" value="<%= campaign.id() %>"><label>Změnit stav<select name="status"><% for (String status : List.of("PLANNED", "ACTIVE", "COMPLETED", "CANCELLED")) { %><option value="<%= status %>" <%= status.equals(campaign.status()) ? "selected" : "" %>><%= status %></option><% } %></select></label><button class="secondary" type="submit">Uložit</button></form></article><% } %></div></section>
<% PromoOptionsView options = (PromoOptionsView) request.getAttribute("options"); %>
<div class="campaign-modal" id="campaign-modal" aria-hidden="true"><div class="campaign-modal-backdrop"></div><section class="campaign-dialog" role="dialog" aria-modal="true" aria-labelledby="campaign-dialog-title"><button type="button" class="dialog-close" id="close-campaign" aria-label="Zavřít">×</button><span class="eyebrow">PRODEJ / PROMO</span><h2 id="campaign-dialog-title">Nová promo kampaň</h2><p>Zadejte plán akce, ceny a plánované množství.</p><form method="post" action="promo" class="campaign-create-form"><input type="hidden" name="action" value="create"><label>Název kampaně<input name="name" required maxlength="200"></label><label>Produkt<select name="productId" required><option value="">Vyberte produkt</option><% if (options != null) for (PromoOptionsView.ProductOption product : options.products()) { %><option value="<%= product.id() %>"><%= product.name() %> (<%= product.unit() %>)</option><% } %></select></label><label>Dodavatel<select name="supplierId" required><option value="">Vyberte dodavatele</option><% if (options != null) for (PromoOptionsView.SupplierOption supplier : options.suppliers()) { %><option value="<%= supplier.id() %>"><%= supplier.name() %></option><% } %></select></label><div class="form-grid"><label>Začátek<input type="date" name="startsOn" required></label><label>Konec<input type="date" name="endsOn" required></label><label>Běžná cena<input type="number" name="regularPrice" min="0" step="0.01" required></label><label>Akční cena<input type="number" name="promoPrice" min="0" step="0.01" required></label><label>Nákupní cena<input type="number" name="supplierPurchasePrice" min="0" step="0.01" required></label><label>Plánované množství<input type="number" name="plannedQuantity" min="0" step="1" required></label><label>Příspěvek dodavatele<input type="number" name="marketingContribution" min="0" step="0.01" value="0" required></label></div><div class="dialog-actions"><button type="button" class="secondary" id="cancel-campaign">Zrušit</button><button type="submit" class="primary">Přidat kampaň</button></div></form></section></div>
<script src="assets/promo.js"></script></main></body></html>