<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="fragments/base-header.jspf" %>
<link rel="stylesheet" href="assets/roles.css?v=20260926-roles2">
<style>.topbar h1{display:none}</style>
<style>.role-mark.custom{background:var(--card-color,#d9ed62)}</style>
<div class="role-toolbar"><button class="primary" id="edit-role" type="button">Upravit roli</button></div>
<section class="section-head"><div><span class="eyebrow">BASE / ACCESS</span><h2>Role a oprávnění</h2><p>Řízení přístupů podle pracovních odpovědností.</p></div><button class="primary" id="add-role" type="button">+ Nová role</button></section><section class="role-grid"><%
	java.util.List<com.example.erp.frontend.base.RolesServlet.RoleView> roles = (java.util.List<com.example.erp.frontend.base.RolesServlet.RoleView>) request.getAttribute("roles");
	if (roles != null) for (com.example.erp.frontend.base.RolesServlet.RoleView role : roles) {
%><article class="role-card" style="--card-color:<%= role.color() %>" data-role-id="<%= role.id() %>" data-color="<%= role.color() %>" data-can-read="<%= role.canRead() %>" data-can-edit="<%= role.canEdit() %>" data-can-manage="<%= role.canManage() %>"><span class="role-mark custom"><%= role.initial() %></span><h3><%= com.example.erp.frontend.base.RolesServlet.escapeHtml(role.name()) %></h3><p><%= com.example.erp.frontend.base.RolesServlet.escapeHtml(role.description()) %></p><b><%= role.userCount() %> uživatelů</b></article><%
	}
%></section>
<div class="role-modal" id="role-modal" aria-hidden="true"><div class="role-modal-backdrop"></div><section class="role-dialog" role="dialog" aria-modal="true" aria-labelledby="role-dialog-title"><button class="dialog-close" id="close-role-dialog" type="button" aria-label="Zavřít">×</button><span class="eyebrow">BASE / ACCESS</span><h2 id="role-dialog-title">Nová role</h2><p>Definujte pracovní odpovědnost a přístup k modulům ERP.</p><form id="role-form"><input type="hidden" name="id" id="role-id"><input type="hidden" name="action" id="role-action" value="create"><label>Název role<input name="name" id="role-name" required maxlength="120" placeholder="Např. Vedoucí prodejny"></label><label>Zkratka<input name="initial" id="role-initial" required maxlength="1" pattern="[A-Za-zÁ-ž]" placeholder="V"></label><label>Popis<textarea name="description" id="role-description" rows="3" maxlength="240" placeholder="Co tato role spravuje?"></textarea></label><fieldset class="permission-fields"><legend>Oprávnění</legend><label><input type="checkbox" name="canRead" id="permission-read" checked> Prohlížet data</label><label><input type="checkbox" name="canEdit" id="permission-edit"> Upravovat záznamy</label><label><input type="checkbox" name="canManage" id="permission-manage"> Spravovat nastavení</label></fieldset><div class="dialog-actions"><button class="secondary-button" id="cancel-role-dialog" type="button">Zrušit</button><button class="primary" type="submit">Vytvořit roli</button></div></form></section></div>
<%@ include file="fragments/base-footer.jspf" %>