ALTER TABLE role_definitions ADD COLUMN color VARCHAR(7) NOT NULL DEFAULT '#D9ED62';
ALTER TABLE erp_companies ADD COLUMN color VARCHAR(7) NOT NULL DEFAULT '#D9ED62';
ALTER TABLE system_users ADD COLUMN color VARCHAR(7) NOT NULL DEFAULT '#DCE9D7';
