ALTER TABLE products
    ADD COLUMN IF NOT EXISTS purchase_price NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS vat_rate NUMERIC(5,2);

ALTER TABLE erp_settings
    ADD COLUMN IF NOT EXISTS eshop_margin_percent NUMERIC(5,2) NOT NULL DEFAULT 30.00,
    ADD COLUMN IF NOT EXISTS eshop_rounding_unit NUMERIC(10,2) NOT NULL DEFAULT 100.00,
    ADD COLUMN IF NOT EXISTS eshop_default_vat_rate NUMERIC(5,2) NOT NULL DEFAULT 21.00;