CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id UUID NOT NULL REFERENCES inventory_items(id),
    product_id UUID NOT NULL REFERENCES products(id),
    product_name VARCHAR(200) NOT NULL,
    sku VARCHAR(60) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    location_name VARCHAR(200) NOT NULL,
    movement_type VARCHAR(20) NOT NULL CHECK (movement_type IN ('OPENING', 'RECEIPT', 'ISSUE')),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    balance_after INTEGER NOT NULL CHECK (balance_after >= 0),
    unit_cost NUMERIC(12,2) NOT NULL CHECK (unit_cost >= 0),
    reference VARCHAR(120) NOT NULL,
    note VARCHAR(500) NOT NULL,
    actor_id UUID,
    actor_name VARCHAR(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_inventory_movements_item ON inventory_movements(inventory_item_id, id DESC);
CREATE INDEX idx_inventory_movements_product ON inventory_movements(product_id);

INSERT INTO inventory_movements (inventory_item_id, product_id, product_name, sku, unit,
    location_name, movement_type, quantity, balance_after, unit_cost, reference, note, actor_name)
SELECT item.id, product.id, product.name, product.sku, product.unit, item.location_name,
    'OPENING', item.quantity, item.quantity, item.unit_cost, 'Počáteční stav',
    'Stav zásob při zavedení evidence pohybů.', 'Migrace'
FROM inventory_items item JOIN products product ON product.id = item.product_id
WHERE item.quantity > 0;
