<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import="com.example.erp.frontend.shop.ShopView" %>
<%@ page import="com.example.erp.frontend.shop.ShopView.Category" %>
<%@ page import="com.example.erp.frontend.shop.ShopView.Product" %>
<%@ page import="com.example.erp.frontend.shop.ShopView.CartLine" %>
<!doctype html>
<html lang="cs">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Fresh Market | E-shop</title><link rel="stylesheet" href="assets/shop.css">
</head>
<body>
<% ShopView shop = (ShopView) request.getAttribute("shop"); String error = request.getParameter("error"); %>
<header class="shop-header"><a class="shop-brand" href="eshop"><span class="brand-mark">F</span><span><strong>FRESH MARKET</strong><small>lokální nákup bez čekání</small></span></a><nav><a href="#catalog">Katalog</a><a href="#delivery">Doručení</a><a class="admin-link" href="ecommerce">Administrace</a></nav><a class="cart-jump" href="#cart">Košík <b><%= shop == null ? 0 : shop.cartCount() %></b></a></header>
<main class="shop-shell">
  <% if (error != null) { %><p class="shop-error"><%= error %></p><% } %>
  <% if (shop == null) { %><section class="shop-error">Katalog se nepodařilo načíst.</section><% } else { %>
  <section class="shop-hero"><div><span class="kicker">DNEŠNÍ VÝBĚR</span><h1>Dobré věci<br><em>na dosah ruky.</em></h1><p>Čerstvé produkty z vašich oblíbených prodejen. Vyberte kategorii, sestavte košík a zvolte způsob doručení.</p><a class="hero-button" href="#catalog">Prohlédnout nabídku <span>↓</span></a></div><div class="hero-stamp"><strong>24 h</strong><span>rychlé doručení<br>domů nebo do boxu</span></div></section>
  <section class="store-layout" id="catalog">
    <aside class="category-nav"><div class="eyebrow">KATALOG</div><h2>Co hledáte?</h2><button class="category-filter active" data-category-filter="all">Všechny produkty <span><%= shop.products().size() %></span></button><% for (Category category : shop.categories()) { %><button class="category-filter" data-category-filter="<%= category.id() %>"><span><%= category.name() %></span><span><%= category.children().size() %></span></button><% if (!category.children().isEmpty()) { %><div class="subcategories"><% for (Category child : category.children()) { %><button class="category-filter" data-category-filter="<%= child.id() %>">↳ <%= child.name() %></button><% } %></div><% } } %><div class="category-note" id="delivery"><strong>Doručení podle vás</strong><p>Domů od zítřka<br>Box od pozítří</p></div></aside>
    <section class="catalog-area"><div class="catalog-heading"><div><span class="eyebrow">FRESH / LOCAL / TODAY</span><h2>Produkty pro každý den</h2></div><span class="result-count" id="result-count"><%= shop.products().size() %> produktů</span></div><div class="shop-products"><% for (Product product : shop.products()) { %><article class="shop-product" data-product-card data-category-id="<%= product.categoryId() == null ? "uncategorized" : product.categoryId() %>"><% if (product.imageUrl() != null && !product.imageUrl().isBlank()) { %><img class="shop-product-image" src="<%= product.imageUrl() %>" alt="<%= product.name() %>"><% } else { %><div class="product-placeholder"><span>FM</span></div><% } %><div class="product-info"><span class="product-sku"><%= product.sku() %></span><h3><%= product.name() %></h3><p><%= product.description() %></p></div><div class="product-buy"><div><strong><%= product.price() %> Kč</strong><small>/ <%= product.unit() %></small></div><span class="stock-label"><%= product.availableQuantity() %> <%= product.unit() %> skladem</span><form method="post"><input type="hidden" name="action" value="add"><input type="hidden" name="productId" value="<%= product.id() %>"><input type="hidden" name="quantity" value="1"><button class="add-button" type="submit" <%= product.availableQuantity() <= 0 ? "disabled" : "" %>><%= product.availableQuantity() <= 0 ? "Vyprodáno" : "Přidat do košíku" %> <span>+</span></button></form></div></article><% } %></div><p class="empty-products" id="empty-products">V této kategorii zatím nejsou žádné produkty.</p></section>
  </section>
  <aside class="cart-panel" id="cart"><div class="cart-heading"><div><span class="eyebrow">VÁŠ NÁKUP</span><h2>Košík</h2></div><span class="cart-count"><%= shop.cartCount() %> ks</span></div><% if (shop.cart().isEmpty()) { %><div class="empty-cart"><span>○</span><h3>Košík čeká na svůj první nákup.</h3><p>Vyberte produkt v katalogu a počet kusů upravíte přímo tady.</p></div><% } else { %><div class="cart-lines"><% for (CartLine line : shop.cart()) { %><article class="cart-line"><div class="cart-line-main"><strong><%= line.product().name() %></strong><small><%= line.product().price() %> Kč / <%= line.product().unit() %></small></div><div class="quantity-control"><form method="post"><input type="hidden" name="action" value="decrease"><input type="hidden" name="productId" value="<%= line.product().id() %>"><button aria-label="Odebrat jeden kus">−</button></form><form method="post"><input type="hidden" name="action" value="set"><input type="hidden" name="productId" value="<%= line.product().id() %>"><input name="quantity" value="<%= line.quantity() %>" min="1" max="<%= line.product().availableQuantity() %>" type="number" aria-label="Počet kusů"></form><form method="post"><input type="hidden" name="action" value="increase"><input type="hidden" name="productId" value="<%= line.product().id() %>"><button aria-label="Přidat jeden kus">+</button></form></div><strong class="line-total"><%= line.lineTotal() %> Kč</strong><form method="post" class="remove-line"><input type="hidden" name="action" value="remove"><input type="hidden" name="productId" value="<%= line.product().id() %>"><button aria-label="Odstranit produkt z košíku">×</button></form></article><% } %></div><div class="cart-summary"><span>Celkem</span><strong><%= shop.cartTotal() %> Kč</strong></div><button class="checkout-button" type="button">Pokračovat k doručení <span>→</span></button><p class="checkout-note">Objednávku dokončíte v dalším kroku.</p><% } %></aside>
  <% } %>
</main><script src="assets/shop.js"></script>
</body></html>
