spring:
  application:
    name: erp-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/erp}
    username: ${DB_USERNAME:erp}
    password: ${DB_PASSWORD:erp}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  server:
    port: 8080
    error:
      include-message: always

  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    schemas: public
    baseline-version: 0
