services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $backendUrl: '%env(resolve:BACKEND_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
