<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ include file="../../fragments/base-header.jspf" %>
<link rel="stylesheet" href="assets/roles.css?v=20260928-154623">
<style>.topbar .breadcrumb{display:none !important}.role-column-mark{background:var(--card-color,#d9ed62)}</style>
<%
    java.util.List<com.example.erp.frontend.base.RolesServlet.RoleView> roles = (java.util.List<com.example.erp.frontend.base.RolesServlet.RoleView>) request.getAttribute("roles");
    com.example.erp.frontend.base.RolesServlet.MatrixView matrix = (com.example.erp.frontend.base.RolesServlet.MatrixView) request.getAttribute("matrix");
%>
<section class="section-head compact"><div><span class="eyebrow">BASE / MODULE ACCESS</span><h2>Role pro moduly</h2><p>Nastavení přístupu jednotlivých rolí k modulům ERP.</p></div><button class="primary" id="save-module-permissions" type="submit" form="module-permissions-form">Uložit oprávnění</button></section>
<form id="module-permissions-form" method="post"><input type="hidden" name="action" value="save-module-permissions"><div class="permissions-table-wrap"><table class="permissions-table"><thead><tr><th>Modul</th><% if (roles != null) for (com.example.erp.frontend.base.RolesServlet.RoleView role : roles) { %><th><span class="role-column-mark" style="--card-color:<%= role.color() %>"><%= role.initial() %></span><%= com.example.erp.frontend.base.RolesServlet.escapeHtml(role.name()) %></th><% } %></tr></thead><tbody><% if (matrix != null && matrix.modules() != null) for (com.example.erp.frontend.base.RolesServlet.ModuleView module : matrix.modules()) { %><tr><th scope="row"><%= com.example.erp.frontend.base.RolesServlet.escapeHtml(module.name()) %></th><% if (roles != null) for (com.example.erp.frontend.base.RolesServlet.RoleView role : roles) { boolean admin = "Administrátor".equals(role.name()); boolean enabled = admin; if (matrix.permissions() != null) for (com.example.erp.frontend.base.RolesServlet.PermissionView permission : matrix.permissions()) if (role.id().equals(permission.roleId()) && module.key().equals(permission.moduleKey())) enabled = true; %><td><input type="checkbox" name="permission_<%= role.id() %>_<%= module.key() %>" <%= enabled ? "checked" : "" %> <%= admin ? "disabled" : "" %> aria-label="<%= com.example.erp.frontend.base.RolesServlet.escapeHtml(module.name()) %> - <%= com.example.erp.frontend.base.RolesServlet.escapeHtml(role.name()) %>"></td><% } %></tr><% } %></tbody></table></div></form>
<%@ include file="../../fragments/base-footer.jspf" %>
